print("Twinkle Twinkle little star\n"
"How I wonder what you are\n"
"Up above the world so high\n"
"Like a diamond in the sky\n"
"Twinkle Twinkle little star\n"
"How I wonder what you are\n"
"When the blazing sun is gone\n"
"When he nothing shines upon\n"
"Then you show your little light\n"
"Twinkle Twinkle little star \n" 
"How I wonder what you are")