a= int(input("Enter first number: "))
b= int(input("Enter second numeber: "))
c= int(input("Enter third number: "))
print("The sum is: "+ str(a+b+c))
print("The avarage is:"+ str((a+b+c)/3))
print("The multiplication is : "+ str(a*b*c))
print("The maximum is: "+ str(max(a,b,c)))
print("The minimum is: "+ str(min(a,b,c)))
print("The absolute value of first number is: "+ str(abs(a)))
