a = int(input("Enter a number 1: "))
b = int(input("Enter a number 2: "))
print("Number a is ", a)
print("Number b is ", b)
print("Sum is  ", a + b)
print("Differecnce is", a - b)
print("Division is", a / b)
print("Multiple is ", a * b)
print("Type of a is ", type(a))
print("Type of b is ", type(b))
