marks=[]
f1 = int(input("Enter the marks that you achieved: "))
marks.append(f1)
f2 = int(input("Enter the marks that you achieved: "))
marks.append(f2)
f2 = int(input("Enter the marks that you achieved: "))
marks.append(f2)
f3 = int(input("Enter the marks that you achieved: "))
marks.append(f3)
f4 = int(input("Enter the marks that you achieved: "))
marks.append(f4)
f5 = int(input("Enter the marks that you achieved: "))
marks.append(f5)
f6 = int(input("Enter the marks that you achieved: "))
marks.append(f6)
f7 = int(input("Enter the marks that you achieved: "))
marks.append(f7)
f8 = int(input("Enter the marks that you achieved: "))
marks.append(f8)
f9 = int(input("Enter the marks that you achieved: "))
marks.append(f9)
f10 = int(input("Enter the marks that you achieved: "))
marks.append(f10)
marks.sort()
print("The marks list: ", marks)